import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7-rc-3/userguide/building_java_projects.html in the Gradle documentation.
 */
plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("com.github.johnrengelman.shadow") version "7.1.2"
}

project.version = "0.4.0"
val prettyName = "Sun Qingqing"
val javaVersion = JavaVersion.VERSION_17

project.extra["scalaMajorVersion"] = "3"
project.extra["scalaVersion"] = "3.6.4-RC1-bin-20241121-5d1d274-NIGHTLY"

repositories {
    // Use Maven Central for resolving dependencies.
    //mavenCentral()
    maven("https://mirrors.cloud.tencent.com/nexus/repository/maven-public/")
    mavenCentral()
}

dependencies {
    implementation("org.scala-lang:scala3-library_3:${project.extra["scalaVersion"]}")
    implementation("org.dromara.hutool:hutool-core:6.0.0-M18")
    implementation("org.dromara.hutool:hutool-http:6.0.0-M18") {
        exclude(group = "org.dromara.hutool", module = "hutool-log")
    }
    implementation("org.dromara.hutool:hutool-setting:6.0.0-M18") {
        exclude(group = "org.dromara.hutool", module = "hutool-log")
    }
    implementation("com.github.valskalla:odin-core_3:0.13.0")
    implementation("org.typelevel:cats-effect_3:3.6-ecf93db")
    implementation("org.virtuslab:scala-yaml_3:0.3.0")
    implementation("org.jetbrains:annotations:26.0.0")
    implementation("com.google.code.gson:gson:2.11.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

application {
    // Define the main class for the application.
    mainClass = "am9.olbcore.onebot.Main"
}

tasks.register<WriteProperties>("generateFile") {
    outputFile = file("$buildDir/resources/main/META-INF/b-info")
    property("version", project.version)
    property("pretty-name", prettyName)
    property("build-time", System.currentTimeMillis())
}

tasks.register<Copy>("copyFile") {
    mustRunAfter("generateFile")
    dependsOn("processResources")
    from("$buildDir/resources/main/META-INF")
    into("$buildDir/classes/java/main/META-INF")
}

tasks.named<JavaCompile>("compileJava") {
    finalizedBy("generateFile")
    finalizedBy("copyFile")
    sourceCompatibility = javaVersion.toString()
    targetCompatibility = javaVersion.toString()
}

tasks.named<ScalaCompile>("compileScala") {
    finalizedBy("generateFile")
    finalizedBy("copyFile")
    sourceCompatibility = javaVersion.toString()
    targetCompatibility = javaVersion.toString()
}

tasks.named<Jar>("jar") {
    from("$buildDir/classes/java/main/META-INF")
}

tasks.named<ShadowJar>("shadowJar") {

    dependsOn("copyFile")
}